/*global define*/
'use strict';
define(['oldmusic/Note'],
function(Note){
  var furElise = [
    [new Note('e4', 1),new Note('e5',0),new Note('c4', 0)],
    [new Note('d#4', 1),new Note('e4', 0)],
    [new Note('e4', 1),new Note('d#4', 0)],
    [new Note('d#4', 1),new Note('e4', 0)],
    [new Note('e4', 1),new Note('d#4', 0)],
    [new Note('b', 1),new Note('e4', 0)],
    [new Note('d4', 1),new Note('b', 0)],
    [new Note('c4', 1),new Note('d4', 0)],
    [new Note('a', 1),new Note('a1', 1)],
    [new Note('e2', 1),new Note('a', 0)],
    [new Note('a2', 1)],
    [new Note('c', 1)],
    [new Note('e', 1)],
    [new Note('a', 1),new Note('e', 0),new Note('c', 0),new Note('a2', 0),new Note('e2', 0),new Note('c4', 0),new Note('a1', 0)],
    [new Note('b', 1),new Note('e1', 1),new Note('a', 0)],
    [new Note('e2', 1),new Note('b', 0)],
    [new Note('g#2', 1)],
    [new Note('e', 1)],
    [new Note('g#', 1)],
    [new Note('b', 1)],
    [new Note('c4', 1),new Note('e1', 0),new Note('e2', 0),new Note('g#2', 0),new Note('e', 0),new Note('g#', 0),new Note('b', 0)],
    /*[new Note('a1', 1)],
    [new Note('e2', 1)],
    [new Note('a2', 1)],
    [new Note('e', 1)],
    [new Note('e4', 1)],
    [new Note('d#4', 1)],
    [new Note('e4', 1)],
    [new Note('d#4', 1)],
    [new Note('e4', 1)],
    [new Note('b', 1)],
    [new Note('d4', 1)],
    [new Note('c4', 1)],
    [new Note('a', 1)],
    [new Note('a1', 1)],
    [new Note('e2', 1)],
    [new Note('a2', 1)],
    [new Note('c', 1)],
    [new Note('e', 1)],
    [new Note('a', 1)],
    [new Note('b', 1)],
    [new Note('e1', 1)],
    [new Note('e2', 1)],
    [new Note('g#2', 1)],
    [new Note('c', 1)],
    [new Note('c4', 1)],
    [new Note('b', 1)],
    [new Note('a', 1)],
    [new Note('a1', 1)],
    [new Note('e2', 1)],
    [new Note('a2', 1)],
    [new Note('b', 1)],
    [new Note('c4', 1)],
    [new Note('d4', 1)],
    [new Note('e4', 1)],
    [new Note('c2', 1)],
    [new Note('g2', 1)],
    [new Note('c', 1)],
    [new Note('g', 1)],
    [new Note('f4', 1)],
    [new Note('e4', 1)],
    [new Note('d4', 1)],
    [new Note('g1', 1)],
    [new Note('g2', 1)],
    [new Note('b2', 1)],
    [new Note('e', 1)],
    [new Note('e4', 1)],
    [new Note('d4', 1)],
    [new Note('c4', 1)],
    [new Note('e1', 1)],
    [new Note('e2', 1)],
    [new Note('e3', 1)],
    [new Note('e4', 1)],*/
    [new Note('e5', 1),'restart'],
  ];
  
  return furElise;
});
